import { APP_VERSION, downloadText, safeFilename, sha256, toast } from "../assets/scientific-ui.js";

export const ANALYSIS_METHODS = {
  endpoint: "last-observation-v1", initialSlope: "ols-initial-window-v1", maximumSlope: "adjacent-maximum-v1",
  auc: "trapezoidal-v1", threshold: "first-crossing-linear-interpolation-v1", snr: "net-signal-over-background-sd-v1"
};

export function parseTimeSeriesCSV(text) {
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter((line) => line.trim());
  if (lines.length < 2) throw new Error("CSV must include a header and at least one data row.");
  const headers = parseCSVLine(lines[0]).map((h) => h.trim().toLowerCase().replace(/[ _-]+/g, ""));
  const find = (...names) => headers.findIndex((header) => names.includes(header));
  const columns = { time: find("time","timestamp","minutes","seconds"), signal: find("signal","value","intensity","test"), background: find("background","bg"), control: find("control","controlsignal"), sample: find("sample","sampleid"), replicate: find("replicate","replicateid") };
  if (columns.time < 0 || columns.signal < 0) throw new Error("CSV requires time and signal columns.");
  const rows = lines.slice(1).map((line, index) => {
    const values = parseCSVLine(line); const time = Number(values[columns.time]); const signal = Number(values[columns.signal]);
    if (!Number.isFinite(time) || !Number.isFinite(signal)) throw new Error(`Row ${index + 2} has an invalid time or signal.`);
    const optional = (column) => column >= 0 && values[column] !== "" ? Number(values[column]) : null;
    return { row: index + 1, time, signal, background: optional(columns.background), control: optional(columns.control), sampleId: columns.sample >= 0 ? values[columns.sample] || "sample-01" : "sample-01", replicateId: columns.replicate >= 0 ? values[columns.replicate] || "rep-1" : "rep-1" };
  });
  const ordered = [...rows].sort((a,b)=>a.sampleId.localeCompare(b.sampleId)||a.replicateId.localeCompare(b.replicateId)||a.time-b.time);
  for (let i=1;i<ordered.length;i+=1) if(ordered[i].sampleId===ordered[i-1].sampleId&&ordered[i].replicateId===ordered[i-1].replicateId&&ordered[i].time<=ordered[i-1].time) throw new Error(`Timestamps must increase within each sample/replicate series (row ${ordered[i].row + 1}).`);
  return ordered;
}

function parseCSVLine(line) {
  const values=[]; let current=""; let quoted=false;
  for(let i=0;i<line.length;i+=1){const char=line[i];if(char==='"'){if(quoted&&line[i+1]==='"'){current+='"';i+=1;}else quoted=!quoted;}else if(char===","&&!quoted){values.push(current.trim());current="";}else current+=char;}
  values.push(current.trim()); return values;
}

export function applyPipeline(rows, config) {
  const baseline = rows[0]?.signal ?? 0;
  let processed = rows.map((row) => {
    let value = row.signal;
    if (config.backgroundSubtract && Number.isFinite(row.background)) value -= row.background;
    if (config.controlNormalize && Number.isFinite(row.control) && row.control !== 0) value /= row.control;
    if (config.baselineCorrect) value -= (config.backgroundSubtract && Number.isFinite(rows[0]?.background) ? baseline - rows[0].background : baseline);
    return { ...row, processed: value };
  });
  if (config.smoothing === "moving-average") {
    const width=Math.max(1,Math.floor(Number(config.window)||3)); const radius=Math.floor(width/2);
    processed=processed.map((row,index)=>{const slice=processed.slice(Math.max(0,index-radius),Math.min(processed.length,index+radius+1));return{...row,processed:mean(slice.map(x=>x.processed))};});
  }
  return processed;
}

export function calculateMetrics(rows, options = {}) {
  const points=[...rows].filter(row=>Number.isFinite(row.time)&&Number.isFinite(row.processed)).sort((a,b)=>a.time-b.time);
  if(points.length<2) throw new Error("At least two valid time points are required.");
  const n=Math.min(points.length,Math.max(2,Math.floor(Number(options.slopeWindow)||3)));
  const initial=linearRegression(points.slice(0,n).map(p=>[p.time,p.processed]));
  const slopes=points.slice(1).map((point,index)=>({value:(point.processed-points[index].processed)/(point.time-points[index].time),from:points[index].time,to:point.time}));
  const method=options.aucMethod||"trapezoidal"; let auc=0;
  for(let i=1;i<points.length;i+=1){const dt=points[i].time-points[i-1].time;auc+=method==="left-rectangle"?dt*points[i-1].processed:dt*(points[i-1].processed+points[i].processed)/2;}
  const threshold=Number(options.threshold); let crossing=null;
  if(Number.isFinite(threshold)) for(let i=1;i<points.length;i+=1){const a=points[i-1],b=points[i];if((a.processed<threshold&&b.processed>=threshold)||(a.processed>threshold&&b.processed<=threshold)){const fraction=(threshold-a.processed)/(b.processed-a.processed);crossing=a.time+fraction*(b.time-a.time);break;}}
  const backgrounds=points.map(p=>p.background).filter(Number.isFinite);const bgSD=sampleSD(backgrounds);const endpoint=points.at(-1).processed;const snr=bgSD>0?endpoint/bgSD:null;
  return {
    endpoint, initialSlope:initial.slope, initialSlopeR2:initial.r2, maximumSlope:Math.max(...slopes.map(x=>x.value)), auc,
    timeToThreshold:crossing, snr, pointCount:points.length,
    methods:{endpoint:ANALYSIS_METHODS.endpoint,initialSlope:`${ANALYSIS_METHODS.initialSlope}; n=${n}`,maximumSlope:ANALYSIS_METHODS.maximumSlope,auc:`${method}-v1; baseline=processed-zero`,timeToThreshold:ANALYSIS_METHODS.threshold,snr:ANALYSIS_METHODS.snr}
  };
}

export function linearRegression(pairs) {
  if(pairs.length<2)return{slope:NaN,intercept:NaN,r2:NaN};const xs=pairs.map(x=>x[0]),ys=pairs.map(x=>x[1]),xm=mean(xs),ym=mean(ys);const denom=xs.reduce((sum,x)=>sum+(x-xm)**2,0);if(denom===0)return{slope:NaN,intercept:NaN,r2:NaN};const slope=pairs.reduce((sum,[x,y])=>sum+(x-xm)*(y-ym),0)/denom;const intercept=ym-slope*xm;const sst=ys.reduce((sum,y)=>sum+(y-ym)**2,0);const sse=pairs.reduce((sum,[x,y])=>sum+(y-(slope*x+intercept))**2,0);return{slope,intercept,r2:sst===0?1:1-sse/sst};
}
export function replicateStatistics(values){const valid=values.filter(Number.isFinite);const m=mean(valid),sd=sampleSD(valid);return{n:valid.length,mean:m,sd,cv:m===0?null:Math.abs(sd/m)*100};}
export function qualityFlags(raw,processed,metrics,options={}){
  const flags=[];const add=(severity,id,message)=>flags.push({severity,id,message});
  if(processed.length<3)add("error","INSUFFICIENT_POINTS","Fewer than three points limits slope and curve review.");
  if(raw.some(row=>!Number.isFinite(row.signal)))add("error","MISSING_SIGNAL","One or more signal values are missing.");
  if(raw.some(row=>row.signal>=65535))add("warning","POSSIBLE_SATURATION","Signal reaches a common 16-bit ceiling; confirm the detector range.");
  if(options.backgroundSubtract&&!raw.some(row=>Number.isFinite(row.background)))add("warning","MISSING_BACKGROUND","Background subtraction is enabled but background values are absent.");
  if(options.controlNormalize&&!raw.some(row=>Number.isFinite(row.control)))add("error","MISSING_CONTROL","Control normalization is enabled but control values are absent.");
  if(!Number.isFinite(metrics.initialSlope))add("error","SLOPE_UNAVAILABLE","Initial slope could not be calculated.");
  if(metrics.initialSlopeR2<.8)add("warning","POOR_INITIAL_LINEARITY",`Initial-window linear fit R² is ${format(metrics.initialSlopeR2)}.`);
  if(!flags.length)add("info","QC_PASS","No configured quality flags were triggered. This is not analytical validation.");
  return flags;
}
function mean(values){return values.length?values.reduce((a,b)=>a+b,0)/values.length:NaN;}
function sampleSD(values){if(values.length<2)return 0;const m=mean(values);return Math.sqrt(values.reduce((sum,v)=>sum+(v-m)**2,0)/(values.length-1));}

if(typeof document!=="undefined")init();

function init(){
  const MAX_FILES=200,MAX_FILE=20*1024*1024,MAX_TOTAL=250*1024*1024;
  const state={raw:[],processed:[],files:[],fileHashes:[],images:[],imageUrls:[],frame:0,rois:[],pipeline:{channel:"grayscale",backgroundSubtract:true,controlNormalize:false,baselineCorrect:false,smoothing:"none",window:3},metrics:null,flags:[],chartSvg:"",overlay:true,drawMode:false,drag:null};
  const experimentId=document.querySelector("#experiment-id");experimentId.value=`exp-${new Date().toISOString().slice(0,10)}-${Math.random().toString(36).slice(2,7)}`;
  const input=document.querySelector("#file-input"),drop=document.querySelector("#drop-zone"),roiCanvas=document.querySelector("#roi-canvas"),ctx=roiCanvas.getContext("2d",{willReadFrequently:true});
  function go(stage){document.querySelectorAll(".stage,.stage-panel").forEach(el=>{const active=(el.dataset.stage||el.dataset.stagePanel)===stage;el.classList.toggle("is-active",active);if(el.classList.contains("stage-panel"))el.hidden=!active;});location.hash=stage;window.scrollTo({top:0,behavior:"smooth"});if(stage==="report")renderReport();}
  document.querySelectorAll("[data-stage],[data-next]").forEach(button=>button.addEventListener("click",()=>go(button.dataset.stage||button.dataset.next)));
  async function handleFiles(files){
    clearImportError();const list=[...files];const total=list.reduce((sum,file)=>sum+file.size,0);
    if(!list.length)return;if(list.length>MAX_FILES)return importError(`Select no more than ${MAX_FILES} files.`);if(list.some(file=>file.size>MAX_FILE))return importError("Each file must be 20 MB or smaller.");if(total>MAX_TOTAL)return importError("The selection exceeds the 250 MB total limit.");
    const csv=list.filter(file=>file.name.toLowerCase().endsWith(".csv"));const images=list.filter(file=>/^image\/(png|jpeg|tiff)$/.test(file.type)||/\.(png|jpe?g|tiff?)$/i.test(file.name));
    if(csv.length&&images.length)return importError("Import either one CSV or an image sequence, not both at once.");if(csv.length!==1&&images.length===0)return importError("Select one CSV or a supported image sequence.");if(list.length!==csv.length+images.length)return importError("Unsupported file type. Executable and archive formats are not accepted.");
    state.files=list;state.fileHashes=await Promise.all(list.map(async file=>({name:file.name,size:file.size,sha256:await sha256(file)})));
    if(csv.length){try{state.raw=parseTimeSeriesCSV(await csv[0].text());state.images=[];revokeImages();renderImportPreview();}catch(error){importError(error.message);}}
    else{state.raw=[];state.images=[...images].sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));revokeImages();state.imageUrls=state.images.map(URL.createObjectURL);state.frame=0;await loadFrame();renderImportPreview();}
  }
  function revokeImages(){state.imageUrls.forEach(URL.revokeObjectURL);state.imageUrls=[];}
  input.addEventListener("change",()=>handleFiles(input.files));drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("is-dragging")});drop.addEventListener("dragleave",()=>drop.classList.remove("is-dragging"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("is-dragging");handleFiles(e.dataTransfer.files)});
  function importError(message){document.querySelector("#import-errors").innerHTML=`<div class="error-state">${escapeHtml(message)}</div>`;state.raw=[];state.images=[];renderImportPreview();}
  function clearImportError(){document.querySelector("#import-errors").replaceChildren();}
  function loadDemo(){state.files=[];state.fileHashes=[{name:"built-in-demo.csv",size:0,sha256:"embedded-demo-v1"}];state.images=[];revokeImages();state.raw=[0,1,2,4,6,8,10,12].map((time,index)=>({row:index+1,time,signal:[18,25,42,78,121,166,198,214][index],background:[12,12,13,13,14,14,15,15][index],control:[110,112,111,114,116,115,117,118][index],sampleId:"demo-low",replicateId:"rep-1"}));document.querySelector("#experiment-name").value="Demo LFIA kinetic series";document.querySelector("#threshold").value="120";renderImportPreview();toast("Demo raw data loaded");}
  document.querySelectorAll('[data-action="demo"]').forEach(button=>button.addEventListener("click",loadDemo));
  function renderImportPreview(){
    const ready=state.raw.length||state.images.length;document.querySelector("#raw-badge").textContent=state.raw.length?`${state.raw.length} rows`:state.images.length?`${state.images.length} frames`:"No data";document.querySelector("#file-summary").textContent=state.files.length?`${state.files.length} file(s), ${formatBytes(state.files.reduce((s,f)=>s+f.size,0))}`:state.raw.length?"Built-in demo data":"Nothing selected";document.querySelector('[data-next="map"]').disabled=!ready;
    if(state.raw.length){const rows=state.raw.slice(0,12);document.querySelector("#import-preview").innerHTML=table(["Time","Sample","Replicate","Signal","Background","Control"],rows.map(r=>[r.time,r.sampleId,r.replicateId,r.signal,r.background??"—",r.control??"—"]))+`<p class="help">Showing ${rows.length} of ${state.raw.length} rows. Timestamps validated within each series.</p>`;}
    else if(state.images.length){document.querySelector("#import-preview").innerHTML=`<div class="image-preview"><img src="${state.imageUrls[0]}" alt="First imported frame"><div><strong>${escapeHtml(state.images[0].name)}</strong><p>${state.images.length} ordered frames. Timestamps will use numbers found in filenames; otherwise frame order.</p><p class="help">Browser TIFF decoding varies. A decoding failure will be reported before analysis.</p></div></div>`;}
    else document.querySelector("#import-preview").innerHTML='<div class="empty-state">Choose files or load the demo to preview raw data.</div>';
    renderROI();renderPreprocessPreview();
  }
  async function loadFrame(){if(!state.imageUrls.length)return;const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error(`Browser could not decode ${state.images[state.frame].name}. Convert it to PNG or JPEG.`));image.src=state.imageUrls[state.frame];});state.currentImage=image;roiCanvas.width=image.naturalWidth;roiCanvas.height=image.naturalHeight;document.querySelector("#frame-scrubber").max=String(state.images.length-1);document.querySelector("#frame-scrubber").value=String(state.frame);document.querySelector("#frame-label").textContent=`Frame ${state.frame+1} / ${state.images.length}`;renderROI();}
  function renderROI(){ctx.clearRect(0,0,roiCanvas.width,roiCanvas.height);if(state.currentImage){ctx.drawImage(state.currentImage,0,0);document.querySelector("#roi-empty").hidden=true;}else{ctx.fillStyle="#202a33";ctx.fillRect(0,0,roiCanvas.width,roiCanvas.height);document.querySelector("#roi-empty").hidden=false;}if(state.overlay)state.rois.filter(r=>!r.hidden).forEach((roi,index)=>{ctx.strokeStyle=roiColor(roi.type);ctx.lineWidth=Math.max(2,roiCanvas.width/450);ctx.strokeRect(roi.x,roi.y,roi.width,roi.height);ctx.fillStyle=roiColor(roi.type);ctx.font=`${Math.max(12,roiCanvas.width/65)}px sans-serif`;ctx.fillText(roi.name,roi.x+4,Math.max(16,roi.y-5));});renderROIList();}
  function renderROIList(){const root=document.querySelector("#roi-list");root.innerHTML=state.rois.length?state.rois.map((roi,index)=>`<div class="roi-item" data-roi="${roi.id}"><label class="field">Name<input data-roi-field="name" value="${escapeHtml(roi.name)}"></label><label class="field">Type<select data-roi-field="type">${["test","control","background","reference"].map(x=>`<option ${x===roi.type?'selected':''}>${x}</option>`).join("")}</select></label><div class="roi-item__fields">${["x","y","width","height"].map(k=>`<label class="field">${k}<input data-roi-field="${k}" type="number" value="${Math.round(roi[k])}"></label>`).join("")}</div><div><button class="icon-button" data-roi-command="duplicate">Duplicate</button><button class="icon-button" data-roi-command="hide">${roi.hidden?'Show':'Hide'}</button><button class="icon-button button--danger" data-roi-command="delete">Delete</button></div></div>`).join(""):'<div class="empty-state">No ROIs. Choose Draw ROI or add a numeric template.</div>';}
  function addROI(){const width=Math.max(40,roiCanvas.width*.18),height=Math.max(30,roiCanvas.height*.12);state.rois.push({id:crypto.randomUUID(),name:`Test ROI ${state.rois.length+1}`,type:"test",x:roiCanvas.width*.4,y:roiCanvas.height*.4,width,height,hidden:false});renderROI();toast("ROI added; drag it on the canvas to move");}
  document.querySelectorAll('[data-roi-action="add"]').forEach(b=>b.addEventListener("click",addROI));document.querySelector('[data-roi-action="overlay"]').addEventListener("click",()=>{state.overlay=!state.overlay;renderROI();});
  document.querySelector("#roi-list").addEventListener("change",e=>{const item=e.target.closest("[data-roi]");if(!item)return;const roi=state.rois.find(r=>r.id===item.dataset.roi);const key=e.target.dataset.roiField;if(!key)return;roi[key]=["x","y","width","height"].includes(key)?Number(e.target.value):e.target.value;validateROI(roi);renderROI();});
  document.querySelector("#roi-list").addEventListener("click",e=>{const item=e.target.closest("[data-roi]");const command=e.target.closest("[data-roi-command]")?.dataset.roiCommand;if(!item||!command)return;const index=state.rois.findIndex(r=>r.id===item.dataset.roi),roi=state.rois[index];if(command==="delete")state.rois.splice(index,1);if(command==="hide")roi.hidden=!roi.hidden;if(command==="duplicate")state.rois.push({...roi,id:crypto.randomUUID(),name:`${roi.name} copy`,x:roi.x+8,y:roi.y+8});renderROI();});
  roiCanvas.addEventListener("pointerdown",e=>{const p=canvasPoint(e);const roi=[...state.rois].reverse().find(r=>!r.hidden&&p.x>=r.x&&p.x<=r.x+r.width&&p.y>=r.y&&p.y<=r.y+r.height);if(roi){state.drag={roi,start:p,origin:{x:roi.x,y:roi.y}};roiCanvas.setPointerCapture(e.pointerId);}});roiCanvas.addEventListener("pointermove",e=>{if(!state.drag)return;const p=canvasPoint(e);state.drag.roi.x=state.drag.origin.x+p.x-state.drag.start.x;state.drag.roi.y=state.drag.origin.y+p.y-state.drag.start.y;validateROI(state.drag.roi);renderROI();});roiCanvas.addEventListener("pointerup",()=>state.drag=null);
  function canvasPoint(e){const rect=roiCanvas.getBoundingClientRect();return{x:(e.clientX-rect.left)*roiCanvas.width/rect.width,y:(e.clientY-rect.top)*roiCanvas.height/rect.height};}
  function validateROI(roi){roi.width=Math.max(1,Math.min(roi.width,roiCanvas.width));roi.height=Math.max(1,Math.min(roi.height,roiCanvas.height));roi.x=Math.max(0,Math.min(roi.x,roiCanvas.width-roi.width));roi.y=Math.max(0,Math.min(roi.y,roiCanvas.height-roi.height));}
  document.querySelector("#frame-scrubber").addEventListener("input",async e=>{state.frame=Number(e.target.value);try{await loadFrame();}catch(error){importError(error.message);}});document.querySelectorAll("[data-frame]").forEach(b=>b.addEventListener("click",async()=>{state.frame=Math.max(0,Math.min(state.images.length-1,state.frame+(b.dataset.frame==="next"?1:-1)));if(state.images.length)await loadFrame();}));
  document.querySelectorAll("[data-pipeline]").forEach(control=>control.addEventListener("change",()=>{state.pipeline[control.dataset.pipeline]=control.type==="checkbox"?control.checked:control.type==="number"?Number(control.value):control.value;renderPreprocessPreview();}));
  function renderPreprocessPreview(){const root=document.querySelector("#preprocess-preview");if(!state.raw.length){root.innerHTML='<div><strong>Before</strong><p class="help">Raw image intensities are extracted only when analysis is run.</p></div><div><strong>After</strong><p class="help">Pipeline configuration is stored in the manifest.</p></div>';return;}const processed=applyPipeline(state.raw,state.pipeline);root.innerHTML=`<div><strong>Before</strong><p>First: ${format(state.raw[0].signal)} · Last: ${format(state.raw.at(-1).signal)}</p><small>Original signal, unchanged</small></div><div><strong>After</strong><p>First: ${format(processed[0].processed)} · Last: ${format(processed.at(-1).processed)}</p><small>${pipelineDescription()}</small></div>`;}
  async function extractImages(){if(!state.images.length)return state.raw;const test=state.rois.find(r=>r.type==="test"&&!r.hidden),background=state.rois.find(r=>r.type==="background"&&!r.hidden),control=state.rois.find(r=>r.type==="control"&&!r.hidden);if(!test)throw new Error("Add and confirm a visible test ROI before analyzing images.");const rows=[];for(let i=0;i<state.imageUrls.length;i+=1){const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=state.imageUrls[i];});const off=document.createElement("canvas");off.width=image.naturalWidth;off.height=image.naturalHeight;const offCtx=off.getContext("2d",{willReadFrequently:true});offCtx.drawImage(image,0,0);const intensity=roi=>roi?roiMean(offCtx,roi,state.pipeline.channel):null;const match=state.images[i].name.match(/(?:^|\D)(\d+(?:\.\d+)?)(?:\D|$)/);rows.push({row:i+1,time:match?Number(match[1]):i,signal:intensity(test),background:intensity(background),control:intensity(control),sampleId:document.querySelector("#sample-id").value||"sample-01",replicateId:document.querySelector("#replicate-id").value||"rep-1"});}return rows;}
  function roiMean(context,roi,channel){const data=context.getImageData(Math.round(roi.x),Math.round(roi.y),Math.max(1,Math.round(roi.width)),Math.max(1,Math.round(roi.height))).data;let total=0;for(let i=0;i<data.length;i+=4)total+=channel==="red"?data[i]:channel==="green"?data[i+1]:channel==="blue"?data[i+2]:.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];return total/(data.length/4);}
  document.querySelector('[data-action="run-analysis"]').addEventListener("click",async()=>{try{const button=document.querySelector('[data-action="run-analysis"]');button.disabled=true;button.textContent="Analyzing…";state.raw=await extractImages();state.processed=applyPipeline(state.raw,state.pipeline);const options=analysisOptions();state.metrics=calculateMetrics(state.processed,options);state.flags=qualityFlags(state.raw,state.processed,state.metrics,{...state.pipeline});renderAnalysis();toast("Analysis complete");}catch(error){toast(error.message,"error");}finally{const button=document.querySelector('[data-action="run-analysis"]');button.disabled=false;button.textContent="Run analysis";}});
  function analysisOptions(){return{slopeWindow:Number(document.querySelector("#slope-window").value),aucMethod:document.querySelector("#auc-method").value,threshold:Number(document.querySelector("#threshold").value)};}
  function renderAnalysis(){const m=state.metrics,timeUnit=document.querySelector("#time-unit").value,signalUnit=processedUnit();const cards=[
    ["Endpoint",m.endpoint,signalUnit,m.methods.endpoint],["Initial slope",m.initialSlope,`${signalUnit}/${timeUnit}`,m.methods.initialSlope],["Maximum slope",m.maximumSlope,`${signalUnit}/${timeUnit}`,m.methods.maximumSlope],["AUC",m.auc,`${signalUnit}·${timeUnit}`,m.methods.auc],["Time to threshold",m.timeToThreshold,timeUnit,m.methods.timeToThreshold],["SNR",m.snr,"ratio",m.methods.snr],["Initial-fit R²",m.initialSlopeR2,"", "OLS goodness of fit"],["Points",m.pointCount,"observations","Valid processed points"]];
    document.querySelector("#metric-cards").innerHTML=cards.map(([label,value,unit,method])=>`<article class="metric-card"><span>${label}</span><strong>${value==null?'Not calculated':format(value)} ${unit}</strong><small>${method}</small></article>`).join("");state.chartSvg=makeChart(state.processed,timeUnit,signalUnit);document.querySelector("#kinetic-chart").innerHTML=state.chartSvg;document.querySelector('[data-action="export-chart"]').disabled=false;document.querySelector('[data-next="validate"]').disabled=false;document.querySelectorAll('[data-action="export-manifest"],[data-action="print"]').forEach(b=>b.disabled=false);renderQC();renderReport();}
  function makeChart(rows,timeUnit,signalUnit){const width=820,height=320,pad={l:64,r:20,t:24,b:54},xs=rows.map(r=>r.time),ys=rows.map(r=>r.processed),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(0,...ys),ymax=Math.max(...ys),x=v=>pad.l+(v-xmin)/Math.max(xmax-xmin,1)*(width-pad.l-pad.r),y=v=>height-pad.b-(v-ymin)/Math.max(ymax-ymin,1)*(height-pad.t-pad.b),path=rows.map((r,i)=>`${i?'L':'M'} ${x(r.time).toFixed(1)} ${y(r.processed).toFixed(1)}`).join(" ");return`<svg viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="chart-title chart-desc" xmlns="http://www.w3.org/2000/svg"><title id="chart-title">Processed kinetic curve</title><desc id="chart-desc">Processed signal over time for ${rows.length} observations.</desc><rect width="100%" height="100%" fill="white"/><path d="M${pad.l} ${pad.t}V${height-pad.b}H${width-pad.r}" fill="none" stroke="#536573"/><path d="${path}" fill="none" stroke="#087067" stroke-width="3"/>${rows.map(r=>`<circle cx="${x(r.time)}" cy="${y(r.processed)}" r="4" fill="#087067"><title>${r.time} ${timeUnit}: ${format(r.processed)} ${signalUnit}</title></circle>`).join("")}<text x="${width/2}" y="${height-12}" text-anchor="middle" fill="#17232f">Time (${timeUnit})</text><text transform="translate(16 ${height/2}) rotate(-90)" text-anchor="middle" fill="#17232f">Processed signal (${signalUnit})</text><text x="${pad.l}" y="${height-pad.b+20}" fill="#5d6e7c">${xmin}</text><text x="${width-pad.r}" y="${height-pad.b+20}" text-anchor="end" fill="#5d6e7c">${xmax}</text><text x="${pad.l-8}" y="${y(ymax)+4}" text-anchor="end" fill="#5d6e7c">${format(ymax)}</text><text x="${pad.l-8}" y="${y(ymin)+4}" text-anchor="end" fill="#5d6e7c">${format(ymin)}</text></svg>`;}
  function renderQC(){const hasError=state.flags.some(f=>f.severity==="error");document.querySelector("#qc-badge").className=`status-badge status-badge--${hasError?'error':state.flags.some(f=>f.severity==='warning')?'warn':'ok'}`;document.querySelector("#qc-badge").textContent=hasError?"QC failure":state.flags.some(f=>f.severity==='warning')?"Review warnings":"Checks passed";document.querySelector("#qc-list").innerHTML=state.flags.map(f=>`<div class="qc-item"><span class="status-badge status-badge--${f.severity==='error'?'error':f.severity==='warning'?'warn':'ok'}">${f.severity}</span><div><strong>${f.id}</strong><p>${escapeHtml(f.message)}</p></div></div>`).join("");document.querySelector("#method-trace").innerHTML=`<dl class="method-list">${Object.entries(state.metrics.methods).map(([key,value])=>`<div><dt>${labelize(key)}</dt><dd>${escapeHtml(value)}</dd></div>`).join("")}</dl>`;}
  async function manifest(){return{schema:"microcd.analyzer.analysis",version:1,experimentId:experimentId.value,experimentName:document.querySelector("#experiment-name").value,applicationVersion:APP_VERSION,createdAt:new Date().toISOString(),execution:"local-browser",rawDataChecksums:state.fileHashes,sampleMetadata:{sampleId:document.querySelector("#sample-id").value,replicateId:document.querySelector("#replicate-id").value,timeUnit:document.querySelector("#time-unit").value,signalUnit:document.querySelector("#signal-unit").value},rois:state.rois.map(r=>({...r})),preprocessing:{...state.pipeline,order:["ROI extraction","channel conversion","background subtraction","control normalization","baseline correction","smoothing"]},analysisParameters:analysisOptions(),formulaIdentifiers:state.metrics?.methods||{},thresholdConfiguration:{enabled:document.querySelector("#classification-enabled").checked,value:Number(document.querySelector("#threshold").value)},warnings:state.flags,qcStatus:state.flags.some(f=>f.severity==="error")?"QC failure":state.flags.some(f=>f.severity==="warning")?"Review warnings":"Checks passed",results:state.metrics};}
  function renderReport(){if(!state.metrics){document.querySelector("#report-summary").innerHTML='<div class="empty-state">Run analysis to create a report.</div>';return;}const status=document.querySelector("#classification-enabled").checked?(state.flags.some(f=>f.severity==="error")?"QC failure":state.metrics.endpoint>=Number(document.querySelector("#threshold").value)?"Above configured threshold":"Below configured threshold"):"No decision rule enabled";document.querySelector("#report-summary").innerHTML=`<h2>${escapeHtml(document.querySelector("#experiment-name").value)}</h2><p><strong>Experiment ID:</strong> ${escapeHtml(experimentId.value)}</p><p><strong>Observations:</strong> ${state.raw.length} raw / ${state.processed.length} processed</p><p><strong>Endpoint:</strong> ${format(state.metrics.endpoint)} ${processedUnit()}</p><p><strong>Initial slope:</strong> ${format(state.metrics.initialSlope)} ${processedUnit()}/${document.querySelector("#time-unit").value}</p><p><strong>Interpretation:</strong> ${status}</p><p><strong>QC:</strong> ${document.querySelector("#qc-badge").textContent}</p><p class="help">Generated locally with Kinetic Assay Analyzer ${APP_VERSION}.</p>`;}
  document.querySelectorAll("[data-report]").forEach(button=>button.addEventListener("click",async()=>{if(!state.metrics)return;const base=safeFilename(document.querySelector("#experiment-name").value,"kinetic-analysis"),type=button.dataset.report;if(type==="raw")downloadText(`${base}-raw.csv`,rowsCSV(state.raw,false),"text/csv");if(type==="processed")downloadText(`${base}-processed.csv`,rowsCSV(state.processed,true),"text/csv");if(type==="results")downloadText(`${base}-results.csv`,resultsCSV(state.metrics),"text/csv");if(type==="manifest")downloadText(`${base}-analysis.json`,JSON.stringify(await manifest(),null,2),"application/json");if(type==="plot")downloadText(`${base}-kinetic-curve.svg`,state.chartSvg,"image/svg+xml");toast("Export downloaded");}));
  document.querySelector('[data-action="export-manifest"]').addEventListener("click",async()=>{if(state.metrics)downloadText(`${safeFilename(document.querySelector("#experiment-name").value)}-analysis.json`,JSON.stringify(await manifest(),null,2),"application/json")});document.querySelectorAll('[data-action="print"]').forEach(b=>b.addEventListener("click",()=>window.print()));document.querySelector('[data-action="export-chart"]').addEventListener("click",()=>downloadText(`${safeFilename(document.querySelector("#experiment-name").value)}-kinetic-curve.svg`,state.chartSvg,"image/svg+xml"));
  document.querySelector('[data-action="reset"]').addEventListener("click",()=>{if(confirm("Start a new experiment? Download current exports first if needed."))location.reload();});
  function processedUnit(){const raw=document.querySelector("#signal-unit").value||"a.u.";return state.pipeline.controlNormalize?"ratio":raw;}
  function pipelineDescription(){return[state.pipeline.channel,state.pipeline.backgroundSubtract?"background subtracted":null,state.pipeline.controlNormalize?"control normalized":null,state.pipeline.baselineCorrect?"baseline corrected":null,state.pipeline.smoothing==="moving-average"?`moving average (${state.pipeline.window})`:null].filter(Boolean).join(" → ");}
  function rowsCSV(rows,includeProcessed){const headers=["row","time","sample_id","replicate_id","signal_raw","background_raw","control_raw",...(includeProcessed?["signal_processed"]:[])];return[headers,...rows.map(r=>[r.row,r.time,r.sampleId,r.replicateId,r.signal,r.background??"",r.control??"",...(includeProcessed?[r.processed]:[])])].map(row=>row.map(csv).join(",")).join("\n");}
  function resultsCSV(m){return[["metric","value","unit","method"],["endpoint",m.endpoint,processedUnit(),m.methods.endpoint],["initial_slope",m.initialSlope,`${processedUnit()}/${document.querySelector("#time-unit").value}`,m.methods.initialSlope],["maximum_slope",m.maximumSlope,`${processedUnit()}/${document.querySelector("#time-unit").value}`,m.methods.maximumSlope],["auc",m.auc,`${processedUnit()}*${document.querySelector("#time-unit").value}`,m.methods.auc],["time_to_threshold",m.timeToThreshold??"",document.querySelector("#time-unit").value,m.methods.timeToThreshold],["snr",m.snr??"","ratio",m.methods.snr]].map(row=>row.map(csv).join(",")).join("\n");}
  if(location.hash&&document.querySelector(`[data-stage="${CSS.escape(location.hash.slice(1))}"]`))go(location.hash.slice(1));renderImportPreview();
}

function table(headers,rows){return`<div class="data-table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;}
function roiColor(type){return({test:"#18c6b4",control:"#ffcc54",background:"#ff7f7f",reference:"#7db7ff"})[type]||"white";}
function format(value){if(value==null||!Number.isFinite(Number(value)))return "Not calculated";const n=Number(value);if(Math.abs(n)>=1e5||(Math.abs(n)<.001&&n!==0))return n.toExponential(3);return new Intl.NumberFormat("en-US",{maximumFractionDigits:4}).format(n);}
function formatBytes(bytes){if(bytes<1024)return`${bytes} B`;if(bytes<1024**2)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1024**2).toFixed(1)} MB`;}
function csv(value){const text=String(value??"");return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
function labelize(value){return value.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase());}
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);}
